In [ ]:
from google.colab import files

files.upload()

In [14]:
 ! mkdir ~/.kaggle

! cp kaggle.json ~/.kaggle/

mkdir: cannot create directory ‘/root/.kaggle’: File exists


In [16]:
 ! chmod 600 ~/.kaggle/kaggle.json

In [17]:
 ! kaggle datasets list

ref                                                         title                                              size  lastUpdated          downloadCount  
----------------------------------------------------------  ------------------------------------------------  -----  -------------------  -------------  
gpreda/reddit-vaccine-myths                                 Reddit Vaccine Myths                              229KB  2021-06-01 11:18:46           6980  
crowww/a-large-scale-fish-dataset                           A Large Scale Fish Dataset                          3GB  2021-04-28 17:03:01           4191  
imsparsh/musicnet-dataset                                   MusicNet Dataset                                   22GB  2021-02-18 14:12:19           1393  
dhruvildave/wikibooks-dataset                               Wikibooks Dataset                                   1GB  2021-02-18 10:08:27           2157  
mathurinache/twitter-edge-nodes                             Twitter Edge Nod

In [18]:
!kaggle datasets download -d therohk/million-headlines

 81% 17.0M/21.1M [00:00<00:00, 52.3MB/s]
100% 21.1M/21.1M [00:00<00:00, 83.5MB/s]


In [19]:
!unzip /content/million-headlines.zip

Archive:  /content/million-headlines.zip
  inflating: abcnews-date-text.csv   


In [20]:
import pandas as pd
npr=pd.read_csv("/content/abcnews-date-text.csv",sep=',')

In [21]:
npr.head()

publish_date                                      headline_text
0      20030219  aba decides against community broadcasting lic...
1      20030219     act fire witnesses must be aware of defamation
2      20030219     a g calls for infrastructure protection summit
3      20030219           air nz staff in aust strike for pay rise
4      20030219      air nz strike to affect australian travellers

In [25]:
len(npr)

1226258

In [ ]:
print(npr.shape)

(1103663, 2)


In [26]:
npr['headline_text'][0]

'aba decides against community broadcasting licence'

In [27]:
from sklearn.feature_extraction.text import CountVectorizer
cv=CountVectorizer(max_df=0.92,min_df=2,max_features=1000,ngram_range=(1,2),lowercase=True,stop_words='english')

In [28]:
cv

CountVectorizer(analyzer='word', binary=False, decode_error='strict',
                dtype=<class 'numpy.int64'>, encoding='utf-8', input='content',
                lowercase=True, max_df=0.92, max_features=1000, min_df=2,
                ngram_range=(1, 2), preprocessor=None, stop_words='english',
                strip_accents=None, token_pattern='(?u)\\b\\w\\w+\\b',
                tokenizer=None, vocabulary=None)

In [29]:
dtm=cv.fit_transform(npr["headline_text"])

In [30]:
dtm

<1226258x1000 sparse matrix of type '<class 'numpy.int64'>'
	with 3181594 stored elements in Compressed Sparse Row format>

In [31]:
from sklearn.decomposition import LatentDirichletAllocation

In [32]:
lda=LatentDirichletAllocation(n_components=5,random_state=42)

In [33]:
lda.fit(dtm)

LatentDirichletAllocation(batch_size=128, doc_topic_prior=None,
                          evaluate_every=-1, learning_decay=0.7,
                          learning_method='batch', learning_offset=10.0,
                          max_doc_update_iter=100, max_iter=10,
                          mean_change_tol=0.001, n_components=5, n_jobs=None,
                          perp_tol=0.1, random_state=42, topic_word_prior=None,
                          total_samples=1000000.0, verbose=0)

In [37]:
len(cv.get_feature_names())

1000

In [38]:
type(cv.get_feature_names())

list

In [39]:
import random
for i in range(10):
  random_word_id=random.randint(0,1000)
  print(cv.get_feature_names()[random_word_id])

plans
goes
years
charge
blaze
coast
boost
12
economy
tourist


In [40]:
# Showing top words in the topic

In [41]:
len(lda.components_)

5

In [42]:
lda.components_.shape

(5, 1000)

In [43]:
lda.components_

array([[2.01020598e-01, 3.98656920e-01, 2.01192880e-01, ...,
        2.01664732e+00, 1.58692287e+00, 2.00600251e-01],
       [3.58260800e+00, 2.08495361e+01, 1.07498849e+02, ...,
        2.61477616e-01, 1.11710138e+03, 2.00227832e-01],
       [2.01783994e-01, 1.25815282e+01, 2.09263625e+02, ...,
        2.06144863e+03, 1.11670043e+03, 2.00827535e-01],
       [2.06962493e-01, 4.30838399e+02, 8.13781007e+02, ...,
        3.78616019e+02, 2.20879303e-01, 1.63719753e+03],
       [2.37280762e+03, 8.52331880e+02, 2.08255326e+02, ...,
        9.34657227e+02, 6.15390381e+02, 2.00811212e-01]])

In [44]:
len(lda.components_[0])

1000

In [45]:
single_topic=lda.components_[0]

In [46]:
single_topic.argsort()

array([202, 575, 753, 640, 151, 967, 923, 534, 300, 532, 380, 893, 274,
       421, 646, 562, 388, 647, 350, 828, 259, 747,  56, 205,  77, 780,
        25, 551, 826, 486, 146,  70, 789, 791,   4, 373,  51, 639, 550,
        24, 779, 104, 458, 325, 218, 443, 999, 582, 781, 377, 379, 447,
        36, 570, 111,  15, 788,  10, 533, 798, 258,  94,  12, 204, 164,
       347, 233,  47, 601, 470,  43, 746, 261, 825, 821, 150,  50, 572,
       128, 267, 694, 201, 689, 944,  21, 195, 338, 476, 132, 812, 813,
       471, 946, 272,  44,  20, 584, 849, 156, 406, 176, 950, 604,   0,
       894, 360, 920,  68, 203, 260, 901, 602, 110, 228, 918, 455,  19,
       313, 478,  14, 512, 772, 116,  66,  65, 328, 995, 269, 372, 475,
       725, 831,   2, 435, 853, 133, 897, 663, 548, 882, 628, 434, 265,
       667, 540,  76,  11, 408, 431, 890, 159,  90, 886, 676, 662, 982,
       979, 688,   6, 976, 910, 565, 752, 968, 257, 145, 519, 683, 314,
       430, 801,  92, 862, 654,   7,  78, 996, 329, 760, 919, 62

In [47]:
# word least represented
single_topic[205]

0.2003664513341731

In [48]:
#word most represented
single_topic[63]

2611.1382671516512

In [49]:
#Top 10 words
single_topic.argsort()[-10:]
top_word_indices=single_topic.argsort()[-10:]
for index in top_word_indices:
  print(cv.get_feature_names()[index])

mp
farmers
cup
missing
north
car
world
plan
interview
says


In [50]:
for index,topic in enumerate(lda.components_):
  print(f'THE TOP 15 WORDS FOR TOPIC: {index}')
  print([cv.get_feature_names()[i] for i in topic.argsort()[-15:]])
  print('\n')


THE TOP 15 WORDS FOR TOPIC: 0
['fight', 'search', 'budget', 'west', 'qld', 'mp', 'farmers', 'cup', 'missing', 'north', 'car', 'world', 'plan', 'interview', 'says']


THE TOP 15 WORDS FOR TOPIC: 1
['abc', 'drug', 'gold', 'face', 'market', 'help', 'murder', 'urged', 'govt', 'coast', 'hospital', 'charged', 'death', 'man', 'police']


THE TOP 15 WORDS FOR TOPIC: 2
['iraq', 'inquiry', 'nt', 'act', 'china', 'rise', 'coronavirus', 'pm', 'deal', 'indigenous', 'minister', 'wins', 'health', 'council', 'australia']


THE TOP 15 WORDS FOR TOPIC: 3
['years', 'family', 'dies', 'woman', 'melbourne', 'sex', 'child', 'home', 'accused', 'killed', 'man', 'court', 'crash', 'sydney', 'new']


THE TOP 15 WORDS FOR TOPIC: 4
['school', 'final', 'national', 'open', 'year', 'claims', 'set', 'wa', 'rural', 'nsw', 'water', 'win', 'government', 'day', 'australian']




In [51]:
# Attaching Discovered topic values to Orginal Articles
dtm.shape

(1226258, 1000)

In [52]:
len(npr)

1226258

In [53]:
topic_result=lda.transform(dtm)

In [54]:
topic_result.shape

(1226258, 5)

In [55]:
topic_result[0]

array([0.10000007, 0.59999725, 0.10000267, 0.10000001, 0.1       ])

In [56]:
topic_result[0].round(2)

array([0.1, 0.6, 0.1, 0.1, 0.1])

In [57]:
topic_result[0].argmax()

1

In [58]:
# Combining with Orginal data

In [59]:
npr.head()

publish_date                                      headline_text
0      20030219  aba decides against community broadcasting lic...
1      20030219     act fire witnesses must be aware of defamation
2      20030219     a g calls for infrastructure protection summit
3      20030219           air nz staff in aust strike for pay rise
4      20030219      air nz strike to affect australian travellers

In [60]:
topic_result.argmax(axis=1)
npr['topic']=topic_result.argmax(axis=1)
npr['publish_date'] = pd.to_datetime(npr['publish_date'].astype(str), format='%Y%m%d')
npr.head(10)

publish_date                                      headline_text  topic
0   2003-02-19  aba decides against community broadcasting lic...      1
1   2003-02-19     act fire witnesses must be aware of defamation      2
2   2003-02-19     a g calls for infrastructure protection summit      4
3   2003-02-19           air nz staff in aust strike for pay rise      4
4   2003-02-19      air nz strike to affect australian travellers      4
5   2003-02-19                  ambitious olsson wins triple jump      2
6   2003-02-19         antic delighted with record breaking barca      0
7   2003-02-19  aussie qualifier stosur wastes four memphis match      3
8   2003-02-19       aust addresses un security council over iraq      2
9   2003-02-19         australia is locked into war timetable opp      2

In [61]:
!pip install mglearn


     |████████████████████████████████| 542kB 7.5MB/s 
  Created wheel for mglearn: filename=mglearn-0.1.9-py2.py3-none-any.whl size=582638 sha256=d5ec7275669e8f4e9a3253365a1d31d5433d93d91343a2e5cb025b9e64045333
  Stored in directory: /root/.cache/pip/wheels/eb/a6/ea/a6a3716233fa62fc561259b5cb1e28f79e9ff3592c0adac5f0
Successfully built mglearn


In [62]:
import mglearn as mg
import numpy as np


In [63]:
sorting =np.argsort(lda.components_)[:,::-1]

In [64]:
features=np.array(cv.get_feature_names())

In [65]:
mg.tools.print_topics(topics=range(5),feature_names=features,sorting = sorting,topics_per_chunk=5,n_words=25)

topic 0       topic 1       topic 2       topic 3       topic 4       
--------      --------      --------      --------      --------      
says          police        australia     new           australian    
interview     man           council       sydney        day           
plan          death         health        crash         government    
world         charged       wins          court         win           
car           hospital      minister      man           water         
north         coast         indigenous    killed        nsw           
missing       govt          deal          accused       rural         
cup           urged         pm            home          wa            
farmers       murder        coronavirus   child         set           
mp            help          rise          sex           claims        
qld           market        china         melbourne     year          
west          face          act           woman         open          
budget